### ISSUE TITLE
FR: Allow user to configure #tag used and perhaps other details (like author)

### ISSUE THREAD

**Issue by verveguy** [verveguy/clip2tana#5]
Should be easy enough to offer a configure page within the extension and save the config to local storage.

**Comment by verveguy** [comment]
Also consider these further configurable options

**Comment by verveguy** [comment]
If both opengraph tags and standard meta tags are present, the extension should grab both - or perhaps let the user specify which to prefer. However, one report says that some sites have og: tags but lack the usual meta tags. So that case is easy: take whatever we can get.

**Comment by verveguy** [comment]
I've added raw support for og: tags in the latest build, 0.0.4.

**Comment by chasinglucid** [comment]
I need to be able to configure the fields as they conflict with my existing ones. I have to go into each copied page and manually change the fields.

**Comment by verveguy** [comment]
I've finally been able to take a fresh run at this and allow configuration. New builds coming soon.

**Comment by verveguy** [comment]
Current beta release include configurable tag support for both the primary node tag and any of the open graph tags (if you want to use them).
